### PR TITLE
Add Quassel-Core

### PR DESCRIPTION
**Pull request by KeinNerd**
This QuasselCore Version is with encryption support.

### CODE REVIEW

**Comment by Roxedus** [comment]
Please rebase to the testing branch

**Comment by Roxedus** [comment]
@KeinNerd Im closing this issue if i get no response in the next few days.

**Comment by Roxedus** [comment]
Before merging to master, what differs from the two currently in CA?

**Comment by KeinNerd** [comment]
@Roxedus it has Encryption Support for BlowFiSH Text Encryption | https://bugs.quassel-irc.org/projects/quassel-irc/wiki/Blowfish_Encryption_Manual - the two other doesnt have this compilied with encrypt support, so i decide to make my own image ;)

**Pull request merged**
