### PR TITLE
Create idrac-fan-controller.xml

### PR DESCRIPTION
**Pull request by sw-carlos-cristobal**
Basing this off of tigerblue77's dockerhub:
https://hub.docker.com/r/tigerblue77/dell_idrac_fan_controller/

and their github repo:
https://github.com/tigerblue77/Dell_iDRAC_fan_controller_Docker

### CODE REVIEW

**Review by Roxedus — APPROVED** [review]

**Comment by tigerblue77** [comment]
Hello @sw-carlos-cristobal,

many thanks for for testing, using and offering my Docker container on the unRAID store. 😁
After discussion with @anthony0030 [here](https://github.com/tigerblue77/Dell_iDRAC_fan_controller_Docker/issues/36), it seems that your description/documentation can be improved/clarified; I'll let you look at that together 😉

Any improvement suggestion is welcome. Thanks again 🚀

**Comment by anthony0030** [comment]
Hi @Roxedus and @sw-carlos-cristobal, I have installed this on my home server and it did not work.
After talking to the author I saw that the template is missing a parameter that allows access to the IPMI controller when running in local mode. the parameter is ```--device=/dev/ipmi0:/dev/ipmi0:rw```. I don't have any experience with making these templates so please add it in. I spent hours trying to figure out why nothing worked. Maybe adding it will save some people time or at least mention it in the description/ extra requirements.

If you need any help please @ me.

**Comment by sw-carlos-cristobal** [comment]
@anthony0030 just to clarify - did adding in that parameter work out as intended? I can easily add this to the extra parameters in the template if it helps out for local runs (I use over LAN so I never encountered that issue sorry!)

**Comment by tigerblue77** [comment]
@sw-carlos-cristobal, I'll let @anthony0030 answer to you but it doesn't just "help", local mode can't work without passing this device to the docker container 😉

**Comment by sw-carlos-cristobal** [comment]
hey @tigerblue77 since I got you here, do you want me to point the link to this repo instead of yours or are you OK with it directing to you?

**Comment by anthony0030** [comment]
I don't know if this is correct but I am guessing a line similar to this needs to be added.

```<Config Name="IPMI Controller" Target="" Default="/dev/ipmi0:/dev/ipmi0" Mode="rw" Description="Container Device: /dev/ipmi0" Type="Device" Display="always" Required="false" Mask="false"/>```

**Comment by tigerblue77** [comment]
Hey @sw-carlos-cristobal, honestly I don't get every detail of what is happening here. If I understand correctly, my Docker container is not shown in unRAID store and pointing directly to my GitHub repository ? If yes, is it downloaded directly from my Docker Hub repository (or ghcr.io) ? Or did you just forked/cloned it to another repository ?

About doc, could you add link to this repo first and mine in second ? Or it isn't possible ? 😉

**Comment by tigerblue77** [comment]
@anthony0030, don't worry you didn't annoyed me much, I'm glad that you try to improve things now ! Sorry about my dry answer the other day, it's always a bit annoying to write docs only to have people come and open issues for things already explained in them 😁

**Comment by sw-carlos-cristobal** [comment]
I have an PR open now for the changes: https://github.com/selfhosters/unRAID-CA-templates/pull/381

Basically I had the problem with the fan noise just destroying my ears and I looked everywhere until I stumbled upon your solution on dockerhub. I went and saw that you had a github repo but there was no easy unraid template for other people to download (I saw tons of requests in old unraid forums for dell idrac solutions with no good answers) so I figured I'd create a template and upload it here. So when I created the template in this repo I had originally pointed the repo link to your github repo which is probably why @anthony0030 ended up on your repo looking for help with unraid. My apologies as I didn't really think about which repo I should have put in but I thought more so that I wanted you to have the credit so I linked yours instead.

In the PR I swapped out this repo for the "support" link but I have your original github and dockerhub links in the description 😃

**Comment by tigerblue77** [comment]
> I saw tons of requests in old unraid forums for dell idrac solutions with no good answers

I'm glad that you found my solution good enough to fit your need ! :)

> My apologies as I didn't really think about which repo I should have put in

No need to apologize! Everything is fine and I'll be happy to help any user of this Docker container. I just can't answer on specific unRAID points nor on points already explained in my documentation (which I tried to make as clear and complete as possible).

> In the PR I swapped out this repo for the "support" link but I have your original github and dockerhub links in the description 😃

I saw your PR and everything seems fine to me, thanks for the credits 😉🚀

**Pull request merged**
