### PR TITLE
Deprecate Chevereto-Free

### PR DESCRIPTION
**Pull request by nwithan8**
Chevereto-Free is deprecated software: https://github.com/rodber/chevereto-free

### CODE REVIEW

**Comment by nwithan8** [comment]
Ugh, linter CI is broken...

**Review by Roxedus — APPROVED** [review]

**Comment by Roxedus** [comment]
> Ugh, linter CI is broken...

i think i just didnt bother to account for moved/removed files

**Comment by rodber** [comment]
;) Chevereto-Free is deprecated but replaced with this: https://github.com/chevereto/chevereto
https://hub.docker.com/r/chevereto/chevereto

**Comment by nwithan8** [comment]
> ;) Chevereto-Free is deprecated but replaced with this: https://github.com/chevereto/chevereto
> https://hub.docker.com/r/chevereto/chevereto

Correct, which already has an Unraid template provided by a different repository.

**Pull request merged**
