### PR TITLE
WIP: Add timezone config to paperless template

### PR DESCRIPTION
**Pull request by Tooa**
## Changes

* Applied `Shave of the XML` section from the [selfhosters guide](https://selfhosters.net/docker/templating/templating/#114-shave-off-the-xml)
* Removed `PAPERLESS_TIME_ZONE` in favor of the `TZ` variable introduced in [this](https://github.com/the-paperless-project/paperless/pull/614) PR. This allows setting the time zone in the container to a value different than UTC. UnRaid implicitly passes the variable on to the container.

### CODE REVIEW

**Comment by gilbN** [comment]
Unraid adds the TZ variable no thats not really needed.

**Comment by Tooa** [comment]
> Unraid adds the TZ variable no thats not really needed.

Ah, I was not aware that UnRaid passes the TZ variable per default to the container. I will then drop the respective commit and adapt the PR to only reflect the shaving changes.

**Comment by Tooa** [comment]
You were a bit too fast with merging. I was also up to remove the `PAPERLESS_TIME_ZONE` variable as it is not necessary anymore. I will open another PR.

**Comment by gilbN** [comment]
:D yeah just noticed lol

**Comment by Tooa** [comment]
I will create a new PR with 

* the shaved XML
* Removed `PAPERLESS_TIME_ZONE` variable

once your PR revert is merged. Sorry for the inconvenience

**Comment by gilbN** [comment]
no worries 👍

**Pull request merged**
