### PR TITLE
Shinobi Pro CCTV official docker hub

### PR DESCRIPTION
**Pull request by jaburges**
direct pull from the shinobi official docker hub to resolve https://github.com/selfhosters/unRAID-CA-templates/issues/195

First template from scratch, so may need an extra review :) hope it has saved some time though

### CODE REVIEW

**Comment by jaburges** [comment]
icon: https://avatars2.githubusercontent.com/u/24641054?s=460&u=48f1530f0bf15da67fda9ab43587cb65d5169d27&v=4

**Comment by Roxedus** [comment]
Rebase to the testing branch

**Comment by gilbN** [comment]
> icon: https://avatars2.githubusercontent.com/u/24641054?s=460&u=48f1530f0bf15da67fda9ab43587cb65d5169d27&v=4

Add the image to /templates/img/

**Comment by jaburges** [comment]
ahhh I didnt have upload permissions to master, but did testing

**Pull request merged**
