### PR TITLE
added airdcpp.xml template

### PR DESCRIPTION
**Pull request by TerrierX**
#132 

Icon URL: https://airdcpp-web.github.io/assets/AirDCPlusPlus.png

### CODE REVIEW

**Comment by Roxedus** [comment]
You are missing `GID` and `UID` from the template.

**Comment by Roxedus** [comment]
Move the ids to the `Default`, rather than as "data"

**Comment by Roxedus** [comment]
Have you tested this? The documentation say to use `/.airdcpp` rather than `/airdcpp`. The documentation is not a typo.

**Comment by TerrierX** [comment]
Yes, if I take `/.airdcpp` the container fails at startup with the following issue:

> .No valid configuration found. Run the application with --configure parameter to set up initial configuration.

`/airdcpp` starts without an issue

It does not download the config files with `/.airdcpp`

**Pull request merged**
