### PR TITLE
Adding Traefik, and an auth middleware

### PR DESCRIPTION
**Pull request by priyankub**
Adding templates for Traefik, which is a reverse proxy, and an auth middleware that works with it.

### CODE REVIEW

**Comment by Roxedus** [comment]
There is already a traefik template in CA

**Comment by priyankub** [comment]
My bad I didn't realize. I can perhaps then just add the forward auth template?

**Comment by Roxedus** [comment]
yea

**Comment by nwithan8** [comment]
@priyankub please reopen a new PR when you want to submit just the forward auth template.

**Pull request closed without merging**
