### PR TITLE
Capitalized S on Shinobi

### PR DESCRIPTION
**Pull request by jaburges**
Also defaults config to /mnt/user/appdata/Shinobi-Pro-CCTV 
different to the directories of /mnt/user/appdata/Shinobi/XXX

### CODE REVIEW

**Comment by jrdnlc** [comment]
Can you elaborate more on how this affects the app itself? or is it just your OCD kicking in? :smiley:

**Comment by jaburges** [comment]
> Can you elaborate more on how this affects the app itself? or is it just your OCD kicking in? 😃

bit of OCD, but i noticed Unraid created multiple folders `shinobi` and `Shinobi` so it wasn't clean.
In theory that doesn't matter as they are mapped, but unnecessary impact on the user to their  `appdata` directory

**Comment by Roxedus** [comment]
It still will be doing that.

**Comment by jaburges** [comment]
> It still will be doing that.

how so ?

the structure should be:

-mnt
----user
-------data
---------Shinobi
---------------config
---------------videos
---------------database


right now I was getting 2 Shinobi folders (`Shinobi` & `shinobi`)
for example
-mnt
-----user
---------data
------------Shinobi
----------------config
------------shinobi
-----------------videos

**Comment by Roxedus** [comment]
> how so ?

You didnt update the autoload. also worth mentioning that the one called `config` gets butchered by CA, as it sets it to the default appdata location, with the container name

**Comment by jaburges** [comment]
> You didnt update the autoload. also worth mentioning that the one called `config` gets butchered by CA, as it sets it to the default appdata location, with the container name

good catch - i'll update
Yeah I noticed that, kinda annoying that it replaces with the container name even with default.

**Comment by Roxedus** [comment]
I dont think there is a good way to solve this at all.

**Comment by jaburges** [comment]
ok - unless we rename all the folders to the `container_name` Shinobi-Pro-CCTV ?

Might solve it as some of the items are hidden in "show more settings"

**Comment by Roxedus** [comment]
As long as the appdata dir is /config, Unraid will void any default, and do {appdata}/{container_name}. Making the subfolder meaningless

**Comment by jaburges** [comment]
> As long as the appdata dir is /config, Unraid will void any default, and do {appdata}/{container_name}. Making the subfolder meaningless

ok so are you saying despite what is already in default, it will actually do this:
/mnt/user/appdata/Shinobi-Pro-CCTV
/mnt/user/appdata/Shinobi-Pro-CCTV/videos
/mnt/user/appdata/Shinobi-Pro-CCTV/customAutoLoad
/mnt/user/appdata/Shinobi-Pro-CCTV/Database

as if I changed the other mapped volumes, then they would all reside in the same directory

**Comment by Roxedus** [comment]
Just `/mnt/user/appdata/shinobi/config`, the rest will be untouched.

**Comment by Roxedus** [comment]
Yea, I don't know if this is something we can fix. The initial motive for this pull-request makes no sense, as the part that differs is based on how Unraid sets the /config.

**Comment by jaburges** [comment]
> Yea, I don't know if this is something we can fix. The initial motive for this pull-request makes no sense, as the part that differs is based on how Unraid sets the /config.

When i tested it and left everything as default i ended up with 3 different folders
shinobi
Shinobi
Shinobi-Pro-CCTV

that doesnt seem optimal for the user

**Comment by Roxedus** [comment]
> shinobi
> Shinobi
> Shinobi-Pro-CCTV

I only get lowercase shinobi. the shm one doesnt really matter, as that is ram. we can only get rid of Shinobi-Pro-CCTV if we rename it, and I think that will cause more confusion.

**Comment by jaburges** [comment]
ok - i'll close in that case

**Pull request closed without merging**
