### PR TITLE
Update Backblaze Icon

### PR DESCRIPTION
**Pull request by smccloud**
Updated the Backblaze icon to their site's favicon.  It is not ideal, but it is what I could find that will work while I search for something better.

### CODE REVIEW

**Comment by nwithan8** [comment]
Please download the image and store it in this repo, and then point the template to the image here.

**Comment by smccloud** [comment]
> Please download the image and store it in this repo, and then point the template to the image here.

Done.

**Review by nwithan8 — APPROVED** [review]

**Comment by nwithan8** [comment]
@Roxedus I believe the linter from #485 is erroneously causing CI to fail here? Or at least isn't providing feedback on what the error is.

**Comment by Roxedus** [comment]
I'm believe it's somewhat due to the fork not being up to date.

**Comment by nwithan8** [comment]
@smccloud Can you rebase your branch on the latest `master` branch here?

**Comment by nwithan8** [comment]
> @nwithan8 Done, sorry. I keep forgetting that step.

No problem, seems like that fixed the issue!

**Pull request merged**
