### PR TITLE
Added Requestrr template

### PR DESCRIPTION
**Pull request by darkalfx**
Add Requestrr template

### CODE REVIEW

**Comment by darkalfx** [comment]
Thank you!

**Comment by darkalfx** [comment]
Was there anything missing or does everything look good?

**Comment by Roxedus** [comment]
Some real source code, and a rebase to the testing branch

**Comment by darkalfx** [comment]
Some real source code? You mean on the Github repository? 
Must I do the rebase to the testing branch, or is that something you guys do to test it?

**Comment by Roxedus** [comment]
`Some real source code?` Yes
`You mean on the Github repository?` I am not comfortable to merge templates for less-known closed-source software
`Must I do the rebase to the testing branch, or is that something you guys do to test it?` We test against out testing branch, pulling the template up in unraid to verify it.

**Comment by darkalfx** [comment]
I pushed all of my source code to the GitHub repository, so feel free to take a look!

Let me know if there's anything else that's missing, I will be more than happy to oblige.

Thank you!

**Comment by darkalfx** [comment]
Alright, I rebased the PR onto Testing so that you guys can test.
I'm guessing you guys will merge and test it now?

**Comment by Roxedus** [comment]
Looks good. Your readme is wrong(PUID, PGID), but the template looks right.

**Comment by darkalfx** [comment]
If you mean that the (PUID, PGID) specified in the readme are not present in the template.

Then it means I forgot to add them in the template... Do I make another PR with the fix?

**Comment by Roxedus** [comment]
Im saying the variables are not actually used, the template is fine.

**Comment by darkalfx** [comment]
Oh you’re right, I updated the readme.

Thanks a ton.

**Pull request merged**
