### PR TITLE
Switch invoiceninja to a repo that added SSL support

### PR DESCRIPTION
**Pull request by mihai-cindea**
This is a fix for invoice ninja.
As you can see from [this long thread](https://forums.unraid.net/topic/83923-help-with-invoiceninja-docker/page/2/?tab=comments#comment-934816) invoiceninja doesn't work on Unraid. 

I've found the reason to mainly be that invoiceninja enforced SSL support by default, and the current docker container doesn't generate any support for it. It uses 443 port, but without any SSL certificates.
I've added my own repo where it generates SSL certs on first run. Or it has the option to provide custom certs as env variables. You can check the source [here](https://github.com/mihai-cindea/invoiceninja).

Also proof that's working: 
image

### CODE REVIEW

**Comment by jrdnlc** [comment]
Switch branch to testing.

**Comment by mihai-cindea** [comment]
> Switch branch to testing.

Done.

**Comment by Roxedus** [comment]
Do you have any infrastructure to keep the image up to date? The guy you forked from has. Could you try Emailing that guy to see if he is willing to accept your changes into his image?

**Comment by mihai-cindea** [comment]
I do have the infrastructure, however I also prefer fixing this at the source. Less to maintain. I just created a PR, will update this once I have feedback. Thanks!

**Comment by Roxedus** [comment]
This was closed because I deleted the branch it was pointed towards, i am still interested in this development.

**Pull request closed without merging**
